#### How should customer journeys be measured?

In this analysis, a customer journey represents the sequence of interactions performed by a customer while attempting to complete the online process. We initially consider each `visit_id` as a candidate customer journey, with its events ordered chronologically using `date_time`.

In [2]:
import pandas as pd

url_web_1 = "https://raw.githubusercontent.com/data-bootcamp-v4/lessons/refs/heads/main/5_6_eda_inf_stats_tableau/project/files_for_project/df_final_web_data_pt_1.txt"
url_web_2 = "https://raw.githubusercontent.com/data-bootcamp-v4/lessons/refs/heads/main/5_6_eda_inf_stats_tableau/project/files_for_project/df_final_web_data_pt_2.txt"

web_1 = pd.read_csv(url_web_1, sep=",")
web_2 = pd.read_csv(url_web_2, sep=",")

df_final_web_data = pd.concat([web_1, web_2], ignore_index=True)
df_final_web_data.shape

(755405, 5)

In [3]:
df_clean_web_data = df_final_web_data.drop_duplicates().reset_index(drop=True)

In [13]:
df_clean_web_data = df_clean_web_data.sort_values(
    ["client_id", "visitor_id", "visit_id", "date_time"]).reset_index(drop=True)
df_clean_web_data

,client_id,visitor_id,visit_id,process_step,date_time
0,169,201385055_71273495308,749567106_99161211863_557568,start,2017-04-12 20:19:36
1,169,201385055_71273495308,749567106_99161211863_557568,step_1,2017-04-12 20:19:45
2,169,201385055_71273495308,749567106_99161211863_557568,step_2,2017-04-12 20:20:31
3,169,201385055_71273495308,749567106_99161211863_557568,step_3,2017-04-12 20:22:05
4,169,201385055_71273495308,749567106_99161211863_557568,confirm,2017-04-12 20:23:09
...,...,...,...,...,...
744636,9999875,738878760_1556639849,931268933_219402947_599432,step_1,2017-06-01 22:40:08
744637,9999875,738878760_1556639849,931268933_219402947_599432,step_1,2017-06-01 22:41:28
744638,9999875,738878760_1556639849,931268933_219402947_599432,step_2,2017-06-01 22:41:47
744639,9999875,738878760_1556639849,931268933_219402947_599432,step_3,2017-06-01 22:44:58
744640,9999875,738878760_1556639849,931268933_219402947_599432,confirm,2017-06-01 22:48:39

In [14]:
hierarchy = (
    df_clean_web_data[["client_id", "visitor_id", "visit_id", "process_step", "date_time"]]
    .sort_values(["client_id", "visitor_id", "visit_id", "date_time"])
    .set_index(["client_id", "visitor_id", "visit_id", "process_step"])
)

hierarchy.head(40)

                                                                                     date_time
client_id visitor_id            visit_id                     process_step
169       201385055_71273495308 749567106_99161211863_557568 start         2017-04-12 20:19:36
                                                             step_1        2017-04-12 20:19:45
                                                             step_2        2017-04-12 20:20:31
                                                             step_3        2017-04-12 20:22:05
                                                             confirm       2017-04-12 20:23:09
336       64757908_3400128256   649044751_80905125055_554468 start         2017-06-01 07:26:55
                                                             start         2017-06-01 07:42:43
546       475037402_89828530214 731811517_9330176838_94847   start         2017-06-17 10:03:29
                                                             step_1        2017-06-17 10:03:39
                                                             step_2        2017-06-17 10:03:52
                                                             step_3        2017-06-17 10:05:19
                                                             confirm       2017-06-17 10:05:42
555       402506806_56087378777 637149525_38041617439_716659 start         2017-04-15 12:57:56
                                                             step_1        2017-04-15 12:58:03
                                                             step_2        2017-04-15 12:58:35
                                                             step_3        2017-04-15 13:00:14
                                                             confirm       2017-04-15 13:00:34
647       66758770_53988066587  40369564_40101682850_311847  start         2017-04-12 15:41:28
                                                             step_1        2017-04-12 15:41:35
                                                             step_2        2017-04-12 15:41:53
                                                             step_3        2017-04-12 15:45:02
                                                             confirm       2017-04-12 15:47:45
722       919259913_64837298108 984487154_55831795985_521110 start         2017-04-19 14:50:10
                                                             step_1        2017-04-19 14:50:20
                                                             step_2        2017-04-19 14:50:56
                                                             step_1        2017-04-19 14:51:12
                                                             start         2017-04-19 14:56:16
                                                             step_1        2017-04-19 14:56:18
                                                             step_2        2017-04-19 14:56:37
                                                             step_3        2017-04-19 14:57:27
                                                             confirm       2017-04-19 15:00:09
786       439747392_30293505155 640294664_79662229470_499394 start         2017-06-01 11:00:22
                                                             start         2017-06-01 11:01:20
                                                             step_1        2017-06-01 11:01:26
                                                             step_2        2017-06-01 11:03:28
                                                             step_3        2017-06-01 11:04:08
                                                             confirm       2017-06-01 11:05:34
805       831412807_82548325803 451173196_11661340552_563345 start         2017-06-15 19:09:13
                                                             step_1        2017-06-15 19:09:19
                                                             step_2        2017-06-15 19:09:26

In [23]:
# sammple 10
sample_visits = (df_clean_web_data["visit_id"].drop_duplicates().sample(10, random_state=42))

In [27]:
sample_journeys[["client_id", "visitor_id", "visit_id", "process_step", "date_time"]]

,client_id,visitor_id,visit_id,process_step,date_time
571217,7660346,920848512_48303294575,149068686_7751908716_517138,start,2017-06-07 14:02:37
571218,7660346,920848512_48303294575,149068686_7751908716_517138,step_1,2017-06-07 14:03:29
571219,7660346,920848512_48303294575,149068686_7751908716_517138,step_2,2017-06-07 14:03:33
571220,7660346,920848512_48303294575,149068686_7751908716_517138,step_3,2017-06-07 14:04:10
571221,7660346,920848512_48303294575,149068686_7751908716_517138,confirm,2017-06-07 14:04:37
318494,4308897,903307072_18441566115,294816096_24993420813_8480,start,2017-06-12 13:51:55
318495,4308897,903307072_18441566115,294816096_24993420813_8480,step_1,2017-06-12 13:52:05
318496,4308897,903307072_18441566115,294816096_24993420813_8480,step_2,2017-06-12 13:52:15
318497,4308897,903307072_18441566115,294816096_24993420813_8480,step_3,2017-06-12 13:53:10
318498,4308897,903307072_18441566115,294816096_24993420813_8480,confirm,2017-06-12 13:53:28
601355,8058289,587835650_14920261368,497065520_197079202_55929,start,2017-06-01 12:13:00
601356,8058289,587835650_14920261368,497065520_197079202_55929,step_1,2017-06-01 12:13:08
601357,8058289,587835650_14920261368,497065520_197079202_55929,step_2,2017-06-01 12:14:58
601358,8058289,587835650_14920261368,497065520_197079202_55929,step_3,2017-06-01 12:19:11
601359,8058289,587835650_14920261368,497065520_197079202_55929,confirm,2017-06-01 12:20:55
430720,5811879,169932591_64136141414,556294106_64589174924_871297,start,2017-03-29 16:46:07
430721,5811879,169932591_64136141414,556294106_64589174924_871297,step_1,2017-03-29 16:46:11
430722,5811879,169932591_64136141414,556294106_64589174924_871297,step_2,2017-03-29 16:46:30
430723,5811879,169932591_64136141414,556294106_64589174924_871297,step_3,2017-03-29 16:47:13
430724,5811879,169932591_64136141414,556294106_64589174924_871297,confirm,2017-03-29 16:47:53
520762,6999674,947965322_20762175374,588721363_75617309094_372199,confirm,2017-05-29 12:36:29
730279,9806840,580424741_41789547449,624914769_4048995281_93397,start,2017-04-23 14:48:09
730280,9806840,580424741_41789547449,624914769_4048995281_93397,step_1,2017-04-23 14:49:40
730281,9806840,580424741_41789547449,624914769_4048995281_93397,step_2,2017-04-23 14:50:12
730282,9806840,580424741_41789547449,624914769_4048995281_93397,step_3,2017-04-23 14:51:03
730283,9806840,580424741_41789547449,624914769_4048995281_93397,confirm,2017-04-23 14:52:10
602392,8073817,913375794_45779018727,691453795_99643043823_672506,start,2017-05-28 13:56:53
602393,8073817,913375794_45779018727,691453795_99643043823_672506,step_1,2017-05-28 13:57:00
602394,8073817,913375794_45779018727,691453795_99643043823_672506,step_2,2017-05-28 13:57:07
602395,8073817,913375794_45779018727,691453795_99643043823_672506,step_3,2017-05-28 13:59:13
602396,8073817,913375794_45779018727,691453795_99643043823_672506,confirm,2017-05-28 13:59:52
225335,3064707,728381282_53732781170,940670184_42520249322_515654,start,2017-04-08 08:42:19
116916,1597347,483891943_50463918725,982627187_29919234690_316752,start,2017-04-15 13:25:01
116917,1597347,483891943_50463918725,982627187_29919234690_316752,step_1,2017-04-15 13:25:43
116918,1597347,483891943_50463918725,982627187_29919234690_316752,step_2,2017-04-15 13:26:00
116919,1597347,483891943_50463918725,982627187_29919234690_316752,step_3,2017-04-15 13:29:23
116920,1597347,483891943_50463918725,982627187_29919234690_316752,confirm,2017-04-15 13:31:03
315596,4270152,38684912_55850598029,986077612_9479710338_570102,start,2017-06-15 13:48:52
315597,4270152,38684912_55850598029,986077612_9479710338_570102,step_1,2017-06-15 13:48:56
315598,4270152,38684912_55850598029,986077612_9479710338_570102,step_2,2017-06-15 13:49:09
315599,4270152,38684912_55850598029,986077612_9479710338_570102,step_3,2017-06-15 13:51:07

In [28]:
journey_sequences = (
    sample_journeys
    .groupby("visit_id")["process_step"]
    .agg(" → ".join)
)

journey_sequences

visit_id
149068686_7751908716_517138     start → step_1 → step_2 → step_3 → confirm
294816096_24993420813_8480      start → step_1 → step_2 → step_3 → confirm
497065520_197079202_55929       start → step_1 → step_2 → step_3 → confirm
556294106_64589174924_871297    start → step_1 → step_2 → step_3 → confirm
588721363_75617309094_372199                                       confirm
624914769_4048995281_93397      start → step_1 → step_2 → step_3 → confirm
691453795_99643043823_672506    start → step_1 → step_2 → step_3 → confirm
940670184_42520249322_515654                                         start
982627187_29919234690_316752    start → step_1 → step_2 → step_3 → confirm
986077612_9479710338_570102               start → step_1 → step_2 → step_3
Name: process_step, dtype: str

In [29]:
# step counts
df_clean_web_data["process_step"].value_counts()

process_step
start      234999
step_1     162797
step_2     132750
step_3     111589
confirm    102506
Name: count, dtype: int64

In [30]:
# visits per step
df_clean_web_data.groupby("process_step")["visit_id"].nunique().sort_values(ascending=False)

process_step
start      144902
step_1     119255
step_2     104341
step_3      95093
confirm     89826
Name: visit_id, dtype: int64

In [34]:
steps_per_visit = (df_clean_web_data.groupby(["visit_id", "process_step"]).size())

steps_per_visit.describe()

count    553417.000000
mean          1.345533
std           0.848505
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max          25.000000
dtype: float64

In [37]:
repeated_steps = steps_per_visit[steps_per_visit > 1]

repeated_steps.index.get_level_values("visit_id").nunique()

68206