Vanguard Project - Vanguard Digital Experience Analysis

Dataset Part1 - https://raw.githubusercontent.com/data-bootcamp-v4/lessons/refs/heads/main/5_6_eda_inf_stats_tableau/project/files_for_project/df_final_web_data_pt_1.txt

Dataset Part2 - https://raw.githubusercontent.com/data-bootcamp-v4/lessons/refs/heads/main/5_6_eda_inf_stats_tableau/project/files_for_project/df_final_web_data_pt_2.txt

In [1]:
# Import Pandas

import pandas as pd

In [2]:
# Load the two datasets

url_pt1 = "https://raw.githubusercontent.com/data-bootcamp-v4/lessons/refs/heads/main/5_6_eda_inf_stats_tableau/project/files_for_project/df_final_web_data_pt_1.txt"
url_pt2 = "https://raw.githubusercontent.com/data-bootcamp-v4/lessons/refs/heads/main/5_6_eda_inf_stats_tableau/project/files_for_project/df_final_web_data_pt_2.txt"

df1 = pd.read_csv(url_pt1)
df2 = pd.read_csv(url_pt2)

In [3]:
# Check df1

print(df1.shape)
df1.head()

(343141, 5)

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

In [4]:
# Check df2 

print(df2.shape)
df2.head()

(412264, 5)

,client_id,visitor_id,visit_id,process_step,date_time
0,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00
1,6019349,442094451_91531546617,154620534_35331068705_522317,confirm,2017-06-01 11:59:27
2,6019349,442094451_91531546617,154620534_35331068705_522317,step_3,2017-06-01 11:58:48
3,6019349,442094451_91531546617,154620534_35331068705_522317,step_2,2017-06-01 11:58:08
4,6019349,442094451_91531546617,154620534_35331068705_522317,step_1,2017-06-01 11:57:58

In [5]:
# Check column and data types for both 

df1.info()
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 343141 entries, 0 to 343140
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     343141 non-null  int64
 1   visitor_id    343141 non-null  str
 2   visit_id      343141 non-null  str
 3   process_step  343141 non-null  str
 4   date_time     343141 non-null  str
dtypes: int64(1), str(4)
memory usage: 13.1 MB
<class 'pandas.DataFrame'>
RangeIndex: 412264 entries, 0 to 412263
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     412264 non-null  int64
 1   visitor_id    412264 non-null  str
 2   visit_id      412264 non-null  str
 3   process_step  412264 non-null  str
 4   date_time     412264 non-null  str
dtypes: int64(1), str(4)
memory usage: 15.7 MB

In [6]:
# Check for missing values for both 

df1.isnull().sum()
df2.isnull().sum()

client_id       0
visitor_id      0
visit_id        0
process_step    0
date_time       0
dtype: int64

In [7]:
# Check for duplicate rows (both dfs)

print("df1 duplicates:", df1.duplicated().sum())
print("df2 duplicates:", df2.duplicated().sum())

df1 duplicates: 2095
df2 duplicates: 8669

In [8]:
# Sanity Check that both dfs have the same columns (Before concatenating)


print(df1.columns.tolist())
print(df2.columns.tolist())
print(df1.columns.equals(df2.columns))

['client_id', 'visitor_id', 'visit_id', 'process_step', 'date_time']
['client_id', 'visitor_id', 'visit_id', 'process_step', 'date_time']
True

In [9]:
# Check for overlap between df1 and df2 (make sure no identical rows exist in both files before stacking them)

overlap = pd.merge(df1, df2, how='inner')
print("Overlapping rows:", len(overlap))

Overlapping rows: 0

In [10]:
# Concatenate df1 and df2 into one dataset (should equal df1.shape[0] + df2.shape[0] rows, same 5 columns)

df_web_data = pd.concat([df1, df2], axis=0, ignore_index=True)

print(df_web_data.shape)
# should equal df1.shape[0] + df2.shape[0] rows, same 5 columns

(755405, 5)

In [11]:
# Verify the combined dataset

df_web_data.info()
df_web_data.isnull().sum()
print("Combined duplicates:", df_web_data.duplicated().sum())
df_web_data.head()

<class 'pandas.DataFrame'>
RangeIndex: 755405 entries, 0 to 755404
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     755405 non-null  int64
 1   visitor_id    755405 non-null  str
 2   visit_id      755405 non-null  str
 3   process_step  755405 non-null  str
 4   date_time     755405 non-null  str
dtypes: int64(1), str(4)
memory usage: 28.8 MB
Combined duplicates: 10764

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

In [12]:
# Save the combined raw dataset to CSV

df_web_data.to_csv("df_web_data_raw_combined.csv", index=False)