### df_final_web_data

In [2]:
import pandas as pd

url_web_1 = "https://raw.githubusercontent.com/data-bootcamp-v4/lessons/refs/heads/main/5_6_eda_inf_stats_tableau/project/files_for_project/df_final_web_data_pt_1.txt"
url_web_2 = "https://raw.githubusercontent.com/data-bootcamp-v4/lessons/refs/heads/main/5_6_eda_inf_stats_tableau/project/files_for_project/df_final_web_data_pt_2.txt"

web_1 = pd.read_csv(url_web_1, sep=",")
web_2 = pd.read_csv(url_web_2, sep=",")

df_final_web_data = pd.concat([web_1, web_2], ignore_index=True)
df_final_web_data.shape

(755405, 5)

In [3]:
web_1.columns == web_2.columns

array([ True,  True,  True,  True,  True])

In [4]:
df_final_web_data.head()

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

In [5]:
df_final_web_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 755405 entries, 0 to 755404
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     755405 non-null  int64
 1   visitor_id    755405 non-null  str
 2   visit_id      755405 non-null  str
 3   process_step  755405 non-null  str
 4   date_time     755405 non-null  str
dtypes: int64(1), str(4)
memory usage: 28.8 MB

In [6]:
df_final_web_data.groupby("client_id")["visitor_id"].nunique()

client_id
169        1
336        1
546        1
555        1
647        1
          ..
9999729    3
9999768    1
9999832    1
9999839    1
9999875    1
Name: visitor_id, Length: 120157, dtype: int64

In [7]:
df_final_web_data.duplicated().sum()

np.int64(10764)

In [8]:
df_clean_web_data = df_final_web_data.drop_duplicates().reset_index(drop=True)

In [9]:
print(df_final_web_data.shape)
print(df_clean_web_data.shape)

(755405, 5)
(744641, 5)

We checked for exact duplicate rows, considering all columns (`client_id`, `visitor_id`, `visit_id`, `process_step` and `date_time`).

A total of 10.764 exact duplicate events were removed because they represent identical event records and could otherwise artificially increase the number of interactions.

Convert date_time column to a datedime type

In [10]:
df_clean_web_data["date_time"]=pd.to_datetime(df_clean_web_data["date_time"]).reset_index(drop=True)
df_clean_web_data["date_time"].dtype

dtype('<M8[us]')

In [11]:
df_clean_web_data.sort_values(["client_id", "visitor_id", "visit_id", "date_time"]).reset_index(drop=True)

,client_id,visitor_id,visit_id,process_step,date_time
0,169,201385055_71273495308,749567106_99161211863_557568,start,2017-04-12 20:19:36
1,169,201385055_71273495308,749567106_99161211863_557568,step_1,2017-04-12 20:19:45
2,169,201385055_71273495308,749567106_99161211863_557568,step_2,2017-04-12 20:20:31
3,169,201385055_71273495308,749567106_99161211863_557568,step_3,2017-04-12 20:22:05
4,169,201385055_71273495308,749567106_99161211863_557568,confirm,2017-04-12 20:23:09
...,...,...,...,...,...
744636,9999875,738878760_1556639849,931268933_219402947_599432,step_1,2017-06-01 22:40:08
744637,9999875,738878760_1556639849,931268933_219402947_599432,step_1,2017-06-01 22:41:28
744638,9999875,738878760_1556639849,931268933_219402947_599432,step_2,2017-06-01 22:41:47
744639,9999875,738878760_1556639849,931268933_219402947_599432,step_3,2017-06-01 22:44:58
744640,9999875,738878760_1556639849,931268933_219402947_599432,confirm,2017-06-01 22:48:39

In [12]:
client_summary=(df_clean_web_data.groupby("client_id").agg(num_visitors=("visitor_id","nunique"), num_visits=("visit_id","nunique")).reset_index())
client_summary.sample(20)

        client_id  num_visitors  num_visits
79636     6640239             1           1
77644     6478827             1           1
43518     3655955             1           2
43033     3614637             2           2
3409       284825             1           1
90844     7563671             1           1
84775     7060925             1           1
107140    8918901             1           1
85563     7129797             1           1
41305     3469548             1           1
85695     7139915             1           1
42929     3606063             1           1
21129     1781072             1           1
110372    9194393             1           1
112240    9341975             1           1
39863     3350550             1           1
80212     6687375             1           2
18337     1547432             1           1
19572     1648608             1           1
28289     2373148             1           1

In [13]:
client_summary["num_visitors"].value_counts().sort_index()

num_visitors
1     110384
2       8407
3       1019
4        226
5         56
6         35
7         19
8          2
10         3
11         4
13         1
14         1
Name: count, dtype: int64

In [14]:
client_summary["num_visits"].describe()

count    120157.000000
mean          1.324201
std           0.741575
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max          21.000000
Name: num_visits, dtype: float64

In [15]:
df_clean_web_data = df_clean_web_data.sort_values(
    ["client_id", "visitor_id", "visit_id", "date_time"]).reset_index(drop=True)
df_clean_web_data

,client_id,visitor_id,visit_id,process_step,date_time
0,169,201385055_71273495308,749567106_99161211863_557568,start,2017-04-12 20:19:36
1,169,201385055_71273495308,749567106_99161211863_557568,step_1,2017-04-12 20:19:45
2,169,201385055_71273495308,749567106_99161211863_557568,step_2,2017-04-12 20:20:31
3,169,201385055_71273495308,749567106_99161211863_557568,step_3,2017-04-12 20:22:05
4,169,201385055_71273495308,749567106_99161211863_557568,confirm,2017-04-12 20:23:09
...,...,...,...,...,...
744636,9999875,738878760_1556639849,931268933_219402947_599432,step_1,2017-06-01 22:40:08
744637,9999875,738878760_1556639849,931268933_219402947_599432,step_1,2017-06-01 22:41:28
744638,9999875,738878760_1556639849,931268933_219402947_599432,step_2,2017-06-01 22:41:47
744639,9999875,738878760_1556639849,931268933_219402947_599432,step_3,2017-06-01 22:44:58
744640,9999875,738878760_1556639849,931268933_219402947_599432,confirm,2017-06-01 22:48:39

In [17]:
hierarchy = (
    df_clean_web_data[["client_id", "visitor_id", "visit_id", "process_step", "date_time"]]
    .sort_values(["client_id", "visitor_id", "visit_id", "date_time"])
    .set_index(["client_id", "visitor_id", "visit_id", "process_step"])
)

hierarchy.head(40)

                                                                                    date_time
client_id visitor_id            visit_id                     process_step
169       201385055_71273495308 749567106_99161211863_557568 start        2017-04-12 20:19:36
                                                             step_1       2017-04-12 20:19:45
                                                             step_2       2017-04-12 20:20:31
                                                             step_3       2017-04-12 20:22:05
                                                             confirm      2017-04-12 20:23:09
336       64757908_3400128256   649044751_80905125055_554468 start        2017-06-01 07:26:55
                                                             start        2017-06-01 07:42:43
546       475037402_89828530214 731811517_9330176838_94847   start        2017-06-17 10:03:29
                                                             step_1       2017-06-17 10:03:39
                                                             step_2       2017-06-17 10:03:52
                                                             step_3       2017-06-17 10:05:19
                                                             confirm      2017-06-17 10:05:42
555       402506806_56087378777 637149525_38041617439_716659 start        2017-04-15 12:57:56
                                                             step_1       2017-04-15 12:58:03
                                                             step_2       2017-04-15 12:58:35
                                                             step_3       2017-04-15 13:00:14
                                                             confirm      2017-04-15 13:00:34
647       66758770_53988066587  40369564_40101682850_311847  start        2017-04-12 15:41:28
                                                             step_1       2017-04-12 15:41:35
                                                             step_2       2017-04-12 15:41:53
                                                             step_3       2017-04-12 15:45:02
                                                             confirm      2017-04-12 15:47:45
722       919259913_64837298108 984487154_55831795985_521110 start        2017-04-19 14:50:10
                                                             step_1       2017-04-19 14:50:20
                                                             step_2       2017-04-19 14:50:56
                                                             step_1       2017-04-19 14:51:12
                                                             start        2017-04-19 14:56:16
                                                             step_1       2017-04-19 14:56:18
                                                             step_2       2017-04-19 14:56:37
                                                             step_3       2017-04-19 14:57:27
                                                             confirm      2017-04-19 15:00:09
786       439747392_30293505155 640294664_79662229470_499394 start        2017-06-01 11:00:22
                                                             start        2017-06-01 11:01:20
                                                             step_1       2017-06-01 11:01:26
                                                             step_2       2017-06-01 11:03:28
                                                             step_3       2017-06-01 11:04:08
                                                             confirm      2017-06-01 11:05:34
805       831412807_82548325803 451173196_11661340552_563345 start        2017-06-15 19:09:13
                                                             step_1       2017-06-15 19:09:19
                                                             step_2       2017-06-15 19:09:26

In [18]:
multiple_start = (
    df_clean_web_data[df_clean_web_data["process_step"] == "start"]
    .groupby("visit_id")
    .size()
)

multiple_start[multiple_start > 1]

visit_id
100019538_17884295066_43909     3
100034012_10293842356_627828    2
100037962_47432393712_705583    3
100105975_18174738494_196339    2
100142091_11599753729_548917    2
                               ..
999890686_31377985689_29808     2
999892866_86068341010_555953    2
99992005_96331220295_164365     2
999960019_60838685252_926860    3
999988789_76411676596_272843    2
Length: 50314, dtype: int64